@host = localhost
@port = 7267
@url = https://{{host}}:{{port}}/api

@admin_token = GET-THE-ADMIN-TOKEN-AND-PUT-IT-HERE
@user_token = GET-THE-USER-TOKEN-AND-PUT-IT-HERE

### Login as admin
POST {{url}}/login
Accept: application/json
Content-Type: application/json

{
  "username": "admin",
  "password": "1234"
}

### Login as user
POST {{url}}/login
Accept: application/json
Content-Type: application/json

{
  "username": "user",
  "password": "4321"
}

### Bad logging
POST {{url}}/login
Accept: application/json
Content-Type: application/json

{
  "username": "asdf",
  "password": "1234"
}

### Get role as admin
GET  {{url}}/login/role
Authorization: Bearer {{admin_token}}
Accept: application/json
Content-Type: application/json

{
  "username": "admin"
}

### Get role as user
GET  {{url}}/login/role
Authorization: Bearer {{user_token}}
Accept: application/json
Content-Type: application/json

{
  "username": "user"
}

### Get invalid user role
GET  {{url}}/login/role
Authorization: Bearer {{admin_token}}
Accept: application/json
Content-Type: application/json

{
  "username": "fasdf"
}

### Get products
GET {{url}}/products/
Authorization: Bearer {{user_token}}
Accept: application/json
Content-Type: application/json

### Create a product as user
POST {{url}}/products/
Authorization: Bearer {{user_token}}
Accept: application/json
Content-Type: application/json

{
  "product": "New product"
}

### Create a product
POST {{url}}/products/
Authorization: Bearer {{admin_token}}
Accept: application/json
Content-Type: application/json

{
  "product": "New product"
}

### Try to create a duplicated
POST {{url}}/products/
Authorization: Bearer {{admin_token}}
Accept: application/json
Content-Type: application/json

{
  "product": "Monitor"
}

### Try to create a bad product
POST {{url}}/products/
Authorization: Bearer {{admin_token}}
Accept: application/json
Content-Type: application/json

{
  "product": ""
}

