@host = localhost
@port = 7267
@url = https://{{host}}:{{port}}/api

@admin_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW4iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbiIsImV4cCI6MTc3OTE5MjY5NCwiaXNzIjoiQXBpRGVtbyIsImF1ZCI6IkFwaURlbW9DbGllbnQifQ.N8K7MQGmKJ7V1pX-81q44q3etv5G0etQYHiyh_zvk_Q
@user_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidXNlciIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IlVzZXIiLCJleHAiOjE3NzkxOTYwMTMsImlzcyI6IkFwaURlbW8iLCJhdWQiOiJBcGlEZW1vQ2xpZW50In0.KdGI9feqi3LvklTHrlYDqsKY9HcAyD63qS1kuQDXYXw

### Login as admin
POST {{url}}/login
Accept: application/json
Content-Type: application/json

{
  "username": "admin",
  "password": "1234"
}

### Login as user
POST {{url}}/login
Accept: application/json
Content-Type: application/json

{
  "username": "user",
  "password": "4321"
}

### Bad logging
POST {{url}}/login
Accept: application/json
Content-Type: application/json

{
  "username": "asdf",
  "password": "1234"
}

### Get role
GET  {{url}}/login/role
Authorization: Bearer {{user_token}}
Accept: application/json
Content-Type: application/json

{
  "username": "user"
}

### Weather
GET {{url}}/weather
Accept: application/json
Content-Type: application/json

### Get products
GET {{url}}/products/
Authorization: Bearer {{user_token}}
Accept: application/json
Content-Type: application/json

### Create a product as user
POST {{url}}/products/
Authorization: Bearer {{user_token}}
Accept: application/json
Content-Type: application/json

{
  "product": "New product"
}

### Create a product
POST {{url}}/products/
Authorization: Bearer {{admin_token}}
Accept: application/json
Content-Type: application/json

{
  "product": "New product"
}

### Try to create a duplicated
POST {{url}}/products/
Authorization: Bearer {{admin_token}}
Accept: application/json
Content-Type: application/json

{
  "product": "Monitor"
}

### Try to create a bad product
POST {{url}}/products/
Authorization: Bearer {{admin_token}}
Accept: application/json
Content-Type: application/json

{
  "product": ""
}

